---
config:
  # Configuration values to set up basic communication
  # Set your COM port e.g. COM3 for Windows, /dev/ttyACM0 for Linux...
  # COM_PORT: "/dev/ttyACM0"
  # COM_PORT: "COM3"
  COM_PORT: "AUTO"

  # Theme to use (located in res/themes)
  # THEME: Terminal_theme
  THEME: 3.5inchTheme2_theme

display:
  # Display size (in portrait orientation)
  DISPLAY_WIDTH: 320
  DISPLAY_HEIGHT: 480

  # Display Brightness
  # Set this as the desired %, 0 being completely dark and 100 being max brightness
  BRIGHTNESS: 20

  # Display orientation is configured by themes

  # Display revision: A or B (for "flagship" version, use B)
  # To identify your revision: https://github.com/mathoudebine/turing-smart-screen-python/wiki/Hardware-revisions
  REVISION: A
