---
config:
  # Configuration values to set up basic communication
  # Set your COM port e.g. COM3 for Windows, /dev/ttyACM0 for Linux...
  # COM_PORT: "/dev/ttyACM0"
  # COM_PORT: "COM3"
  COM_PORT: "AUTO"

  # Theme to use (located in res/themes)
  # THEME: Terminal
  # THEME: Landscape6Grid
  # THEME: Cyberpunk
  # THEME: bash-dark-green
  THEME: 3.5inchTheme2

  # Hardware sensors reading
  # Choose the appropriate method for reading your hardware sensors:
  # - PYTHON  use Python libraries (psutils, GPUtil...) to read hardware sensors (supports all OS but not all HW)
  # - LHM     use LibreHardwareMonitor library to read hardware sensors (Windows only - NEEDS ADMIN RIGHTS)
  # - STUB    use fake random data instead of real hardware sensors
  # - AUTO    use the best method based on your OS: Windows OS will use LHM, other OS will use Python libraries
  HW_SENSORS: AUTO

  # Network interfaces
  # Linux/MacOS interfaces are named "eth0", "wlan0", "wlp1s0", "enp2s0"...
  # For Windows use the interfaces pretty name: "Ethernet 2", "Wi-Fi", ...
  # Leave the fields empty if the card does not exist on your setup
  ETH: "eth0" # Ethernet Card
  WLO: "wlan0" # Wi-Fi Card

display:
  # Display resolution in portrait orientation
  # Do not use this setting to rotate display! Display orientation is managed by themes
  DISPLAY_WIDTH: 320
  DISPLAY_HEIGHT: 480

  # Display Brightness
  # Set this as the desired %, 0 being completely dark and 100 being max brightness
  # Warning: screen can get very hot at high brightness!
  BRIGHTNESS: 20

  # Display revision: A or B (for "flagship" version, use B) or SIMU for simulated LCD (image written in screencap.png)
  # To identify your revision: https://github.com/mathoudebine/turing-smart-screen-python/wiki/Hardware-revisions
  REVISION: A
